# HI NUMPY

In [1]:
import numpy as np

In [2]:
myarr= np.array([[1,2,3,4,5]],np.int8)

In [3]:
myarr

array([[1, 2, 3, 4, 5]], dtype=int8)

In [4]:
print(myarr)

[[1 2 3 4 5]]


In [5]:
myarr[0]

array([1, 2, 3, 4, 5], dtype=int8)

In [6]:
myarr[0,1]

np.int8(2)

In [7]:
arr= np.array([1,2,3,4,5])

In [8]:
arr[3]

np.int64(4)

In [9]:
arr.shape

(5,)

In [10]:
myarr.shape

(1, 5)

In [11]:
myarr.dtype

dtype('int8')

In [12]:
arr.dtype

dtype('int64')

In [13]:
myarr[0,1]=45

In [14]:
myarr

array([[ 1, 45,  3,  4,  5]], dtype=int8)

# Array Creation :Conversion from other Python structures

In [15]:
listarray= np.array([[1,2,3],[5,8,5],[0,3,1]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarray.shape,listarray.dtype,listarray.size

((3, 3), dtype('int64'), 9)

In [18]:
np.array({2,3,5})

array({2, 3, 5}, dtype=object)

# Array Creation : Intrinsic NumPy array creation functions 

In [19]:
zeros= np.zeros((1,2))

In [20]:
zeros

array([[0., 0.]])

In [21]:
rng= np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,5,12)

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
l=np.linspace(1,5,4)

In [26]:
l

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [27]:
em= np.empty((4,6))

In [28]:
em

array([[6.95271623e-310, 6.95271621e-310, 0.00000000e+000,
        5.32620944e-312, 1.38423532e-311, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 1.38423759e-311],
       [2.22518251e-306, 1.33511969e-306, 0.00000000e+000,
        1.38423758e-311, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 5.68175493e-322, 1.02359984e-306,
        6.23055651e-307, 1.69121096e-306,             nan]])

In [29]:
empl=np.empty_like(l)

In [30]:
empl

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [31]:
ide= np.identity(4)

In [32]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
arr=np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr1=arr.ravel()

In [43]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr1.shape

(99,)

In [38]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [39]:
ar=np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [59]:
ar.argmax()

np.int64(6)

In [64]:
ar.argmax(axis=0)

array([2, 1, 1])

In [61]:
ar.argmin()

np.int64(8)

In [63]:
ar.argmin(axis=0)

array([0, 2, 2])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [68]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [46]:
ar.flat

In [47]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [49]:
ar.ndim

2

In [50]:
ar.size

9

In [52]:
one=np.array([1,3,4,532,74])

In [54]:
one.argmax()

np.int64(3)

In [55]:
one.argmin()

np.int64(0)

In [56]:
one.argsort()

array([0, 1, 2, 4, 3])

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar2=np.array([[1,2,1],[4,0,6],[15,2,8]])

In [71]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [22,  3,  8]])

In [72]:
ar*ar2

array([[  1,   4,   3],
       [ 16,   0,  36],
       [105,   2,   0]])

In [74]:
np.sqrt(ar+ar2)

array([[1.41421356, 2.        , 2.        ],
       [2.82842712, 2.23606798, 3.46410162],
       [4.69041576, 1.73205081, 2.82842712]])

In [75]:
ar.max()

np.int64(7)

In [76]:
ar.min()

np.int64(0)

In [78]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [80]:
np.count_nonzero(ar)

8